In [23]:
import pandas as pd

In [24]:
import numpy as np

In [25]:
data=np.random.randn(4,3)

In [26]:
data

array([[ 2.49162895,  1.24536031,  1.16400912],
       [-0.8197354 , -1.01374904,  0.62509333],
       [-0.96750474, -0.52643519, -2.66142903],
       [ 0.18551142,  0.10485268,  0.19067747]])

In [27]:
data_frame=pd.DataFrame(data)

In [28]:
data_frame

          0         1         2
0  2.491629  1.245360  1.164009
1 -0.819735 -1.013749  0.625093
2 -0.967505 -0.526435 -2.661429
3  0.185511  0.104853  0.190677

In [29]:
type(data_frame)

pandas.core.frame.DataFrame

In [30]:
type(data_frame[0])

pandas.core.series.Series

In [57]:
new_df=pd.DataFrame(data,index=["Ali","Veli","Ayse","Fatma"],columns=["salary","age","senioroty"])

In [58]:
new_df

         salary       age  senioroty
Ali    2.491629  1.245360   1.164009
Veli  -0.819735 -1.013749   0.625093
Ayse  -0.967505 -0.526435  -2.661429
Fatma  0.185511  0.104853   0.190677

In [59]:
new_df["age"]

Ali      1.245360
Veli    -1.013749
Ayse    -0.526435
Fatma    0.104853
Name: age, dtype: float64

In [60]:
new_df["salary"]

Ali      2.491629
Veli    -0.819735
Ayse    -0.967505
Fatma    0.185511
Name: salary, dtype: float64

In [61]:
new_df[["salary","age"]]

         salary       age
Ali    2.491629  1.245360
Veli  -0.819735 -1.013749
Ayse  -0.967505 -0.526435
Fatma  0.185511  0.104853

In [62]:
new_df.loc["Veli"]

salary      -0.819735
age         -1.013749
senioroty    0.625093
Name: Veli, dtype: float64

In [63]:
new_df.iloc[2]
# index olarak getirmek için iloc kullanılır

salary      -0.967505
age         -0.526435
senioroty   -2.661429
Name: Ayse, dtype: float64

In [64]:
new_df.iloc[:,2]
# once satır indexi sonra sutun indexi 
# burda : işareti tüm satırları al ve sadece 2.sutunu al

Ali      1.164009
Veli     0.625093
Ayse    -2.661429
Fatma    0.190677
Name: senioroty, dtype: float64

In [65]:
new_df

         salary       age  senioroty
Ali    2.491629  1.245360   1.164009
Veli  -0.819735 -1.013749   0.625093
Ayse  -0.967505 -0.526435  -2.661429
Fatma  0.185511  0.104853   0.190677

In [66]:
new_df["Extra"]=10

In [67]:
new_df

         salary       age  senioroty  Extra
Ali    2.491629  1.245360   1.164009     10
Veli  -0.819735 -1.013749   0.625093     10
Ayse  -0.967505 -0.526435  -2.661429     10
Fatma  0.185511  0.104853   0.190677     10

In [68]:
new_df.drop("Extra",axis=1,inplace=True)
# sutunu silmek için axis=1 yazdık

In [69]:
new_df

         salary       age  senioroty
Ali    2.491629  1.245360   1.164009
Veli  -0.819735 -1.013749   0.625093
Ayse  -0.967505 -0.526435  -2.661429
Fatma  0.185511  0.104853   0.190677

In [70]:
new_df.drop("Veli", axis=0)

         salary       age  senioroty
Ali    2.491629  1.245360   1.164009
Ayse  -0.967505 -0.526435  -2.661429
Fatma  0.185511  0.104853   0.190677

In [71]:
#asagıdakki kod satir secer
new_df.loc["Ayse"]

salary      -0.967505
age         -0.526435
senioroty   -2.661429
Name: Ayse, dtype: float64

In [72]:
new_df.loc["Ayse","age"]

np.float64(-0.5264351877691975)

In [74]:
boolean_frame=new_df>0

In [77]:
boolean_frame
# sıfırdan büyük olup olmamasına bakılarak true false döner

       salary    age  senioroty
Ali      True   True       True
Veli    False  False       True
Ayse    False  False      False
Fatma    True   True       True

In [78]:
new_df[boolean_frame]

         salary       age  senioroty
Ali    2.491629  1.245360   1.164009
Veli        NaN       NaN   0.625093
Ayse        NaN       NaN        NaN
Fatma  0.185511  0.104853   0.190677

In [79]:
new_df[new_df["salary"]>0.1]

         salary       age  senioroty
Ali    2.491629  1.245360   1.164009
Fatma  0.185511  0.104853   0.190677

In [83]:
new_df[new_df["age"]>1]

       salary      age  senioroty
Ali  2.491629  1.24536   1.164009

In [84]:
new_df.reset_index()

   index    salary       age  senioroty
0    Ali  2.491629  1.245360   1.164009
1   Veli -0.819735 -1.013749   0.625093
2   Ayse -0.967505 -0.526435  -2.661429
3  Fatma  0.185511  0.104853   0.190677

In [85]:
first_index = ["Argentina","Argentina","Portugal",
               "Brazil","Brazil","France"]

In [86]:
inner_index = ["Messi","Di Maria","Ronaldo",
               "Neymar","Ronaldinho","Mbappe"]

In [90]:
zipped_index = list(zip(first_index, inner_index))

In [92]:
zipped_index

[('Argentina', 'Messi'),
 ('Argentina', 'Di Maria'),
 ('Portugal', 'Ronaldo'),
 ('Brazil', 'Neymar'),
 ('Brazil', 'Ronaldinho'),
 ('France', 'Mbappe')]

In [93]:
zipped_index=pd.MultiIndex.from_tuples(zipped_index)

In [94]:
zipped_index

MultiIndex([('Argentina',      'Messi'),
            ('Argentina',   'Di Maria'),
            ( 'Portugal',    'Ronaldo'),
            (   'Brazil',     'Neymar'),
            (   'Brazil', 'Ronaldinho'),
            (   'France',     'Mbappe')],
           )

In [96]:
sample_values = np.array([
    [36, 800],   # Messi
    [35, 150],   # Di Maria
    [39, 850],   # Ronaldo
    [32, 400],   # Neymar
    [44, 300],   # Ronaldinho
    [25, 250]    # Mbappe
])

In [98]:
big_df=pd.DataFrame(sample_values,index=zipped_index,columns=["Age","Goals"])

In [99]:
print(big_df.loc["Argentina"])

          Age  Goals
Messi      36    800
Di Maria   35    150

In [100]:
print(big_df.loc["Argentina"].loc["Messi"])

Age       36
Goals    800
Name: Messi, dtype: int64

In [101]:
big_df

                      Age  Goals
Argentina Messi        36    800
          Di Maria     35    150
Portugal  Ronaldo      39    850
Brazil    Neymar       32    400
          Ronaldinho   44    300
France    Mbappe       25    250

In [102]:
big_df.loc["Brazil"].loc["Neymar"]

Age       32
Goals    400
Name: Neymar, dtype: int64