In [5]:
import pandas as pd

In [6]:
df=pd.read_csv("8-apply_function_data.csv")

In [7]:
df

    Employee_ID     Name Department  Salary  Experience  Performance_Score
0             1    Emp_1  Marketing   82251           6                  5
1             2    Emp_2      Sales   52662          24                  3
2             3    Emp_3    Finance   38392           5                  3
3             4    Emp_4      Sales   60535          20                  3
4             5    Emp_5      Sales  108603           2                  2
..          ...      ...        ...     ...         ...                ...
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

[100 rows x 6 columns]

In [8]:
df.head()

   Employee_ID   Name Department  Salary  Experience  Performance_Score
0            1  Emp_1  Marketing   82251           6                  5
1            2  Emp_2      Sales   52662          24                  3
2            3  Emp_3    Finance   38392           5                  3
3            4  Emp_4      Sales   60535          20                  3
4            5  Emp_5      Sales  108603           2                  2

In [9]:
df.tail()

    Employee_ID     Name Department  Salary  Experience  Performance_Score
95           96   Emp_96    Finance   93734          19                  4
96           97   Emp_97      Sales  100467          22                  2
97           98   Emp_98         IT   82662          23                  3
98           99   Emp_99         IT   42688          22                  1
99          100  Emp_100         HR   55342          14                  3

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        100 non-null    int64
 1   Name               100 non-null    object
 2   Department         100 non-null    object
 3   Salary             100 non-null    int64
 4   Experience         100 non-null    int64
 5   Performance_Score  100 non-null    int64
dtypes: int64(4), object(2)
memory usage: 4.8+ KB

In [14]:
df.columns

Index(['Employee_ID', 'Name', 'Department', 'Salary', 'Experience',
       'Performance_Score'],
      dtype='object')

In [15]:
df[1:35]

    Employee_ID    Name Department  Salary  Experience  Performance_Score
1             2   Emp_2      Sales   52662          24                  3
2             3   Emp_3    Finance   38392           5                  3
3             4   Emp_4      Sales   60535          20                  3
4             5   Emp_5      Sales  108603           2                  2
5             6   Emp_6         IT   82256           6                  5
6             7   Emp_7    Finance  119135          22                  1
7             8   Emp_8    Finance   65222          11                  4
8             9   Emp_9    Finance  107373          16                  1
9            10  Emp_10      Sales  109575          16                  5
10           11  Emp_11  Marketing  114651           1                  4
11           12  Emp_12    Finance   93335           9                  5
12           13  Emp_13      Sales   40965           6                  3
13           14  Emp_14         IT   54538          16                  4
14           15  Emp_15  Marketing  100592           3                  3
15           16  Emp_16         IT   38110          20                  1
16           17  Emp_17  Marketing  109309           4                  1
17           18  Emp_18      Sales   57266          19                  4
18           19  Emp_19         HR   82992           3                  4
19           20  Emp_20  Marketing  112948          19                  5
20           21  Emp_21         IT   36910          20                  5
21           22  Emp_22      Sales   30206           7                  3
22           23  Emp_23  Marketing  117054          20                  4
23           24  Emp_24         HR  117897           9                  1
24           25  Emp_25         HR   53419           1                  5
25           26  Emp_26    Finance   80636           8                  5
26           27  Emp_27    Finance   80015           7                  1
27           28  Emp_28         IT   84268          18                  5
28           29  Emp_29  Marketing  117939           8                  3
29           30  Emp_30  Marketing   48141           1                  4
30           31  Emp_31    Finance  110356          11                  1
31           32  Emp_32  Marketing  101910          18                  4
32           33  Emp_33  Marketing   86044          23                  5
33           34  Emp_34         HR   97214          10                  5
34           35  Emp_35    Finance   63827           3                  1

In [19]:
def salary_category(salary):
    if salary<=50000:
        return "low"
    elif 50000<salary<=80000:
        return "medium"
    else:
        return "high"

In [20]:
df["Salary"].apply(salary_category)

0       high
1     medium
2        low
3     medium
4       high
       ...
95      high
96      high
97      high
98       low
99    medium
Name: Salary, Length: 100, dtype: object

In [21]:
df["Salary_Category"]=df["Salary"].apply(salary_category)

In [22]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category
0,1,Emp_1,Marketing,82251,6,5,high
1,2,Emp_2,Sales,52662,24,3,medium
2,3,Emp_3,Finance,38392,5,3,low
3,4,Emp_4,Sales,60535,20,3,medium
4,5,Emp_5,Sales,108603,2,2,high
...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high
96,97,Emp_97,Sales,100467,22,2,high
97,98,Emp_98,IT,82662,23,3,high
98,99,Emp_99,IT,42688,22,1,low
99,100,Emp_100,HR,55342,14,3,medium

In [27]:
def adjust_performance(Experience):
    if Experience>10:
        return 1
    else :
        return 0

In [29]:
df["Adjusted"]=df["Experience"].apply(adjust_performance)

In [32]:
df["new_score"]=df["Adjusted"] + df["Performance_Score"]

In [33]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,new_score
0,1,Emp_1,Marketing,82251,6,5,high,0,5
1,2,Emp_2,Sales,52662,24,3,medium,1,4
2,3,Emp_3,Finance,38392,5,3,low,0,3
3,4,Emp_4,Sales,60535,20,3,medium,1,4
4,5,Emp_5,Sales,108603,2,2,high,0,2
...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high,1,5
96,97,Emp_97,Sales,100467,22,2,high,1,3
97,98,Emp_98,IT,82662,23,3,high,1,4
98,99,Emp_99,IT,42688,22,1,low,1,2
99,100,Emp_100,HR,55342,14,3,medium,1,4

In [34]:
def adjust_new(row):
    if row["Experience"]>10:
        return row["Performance_Score"]
    else:
        return row["Performance_Score"]

In [36]:
df["Adjusted_Score"]=df.apply(adjust_new,axis=1)

In [37]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,new_score,Adjusted_Score
0,1,Emp_1,Marketing,82251,6,5,high,0,5,5
1,2,Emp_2,Sales,52662,24,3,medium,1,4,3
2,3,Emp_3,Finance,38392,5,3,low,0,3,3
3,4,Emp_4,Sales,60535,20,3,medium,1,4,3
4,5,Emp_5,Sales,108603,2,2,high,0,2,2
...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high,1,5,4
96,97,Emp_97,Sales,100467,22,2,high,1,3,2
97,98,Emp_98,IT,82662,23,3,high,1,4,3
98,99,Emp_99,IT,42688,22,1,low,1,2,1
99,100,Emp_100,HR,55342,14,3,medium,1,4,3

In [42]:
df["Formatted_Name"] = df["Name"].apply(lambda x: x.replace("_", " "))

In [43]:
df

,Employee_ID,Name,Department,Salary,Experience,Performance_Score,Salary_Category,Adjusted,new_score,Adjusted_Score,Formatted_name,Formatted_Name
0,1,Emp_1,Marketing,82251,6,5,high,0,5,5,Emp 1,Emp 1
1,2,Emp_2,Sales,52662,24,3,medium,1,4,3,Emp 2,Emp 2
2,3,Emp_3,Finance,38392,5,3,low,0,3,3,Emp 3,Emp 3
3,4,Emp_4,Sales,60535,20,3,medium,1,4,3,Emp 4,Emp 4
4,5,Emp_5,Sales,108603,2,2,high,0,2,2,Emp 5,Emp 5
...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,Emp_96,Finance,93734,19,4,high,1,5,4,Emp 96,Emp 96
96,97,Emp_97,Sales,100467,22,2,high,1,3,2,Emp 97,Emp 97
97,98,Emp_98,IT,82662,23,3,high,1,4,3,Emp 98,Emp 98
98,99,Emp_99,IT,42688,22,1,low,1,2,1,Emp 99,Emp 99
99,100,Emp_100,HR,55342,14,3,medium,1,4,3,Emp 100,Emp 100